version: '3.7'
services:

  redis:
    image: redis:5.0.5
    environment:
      REDIS_HOST: redis
      REDIS_PORT: 6379
    ports:
      - 6379:6379
    networks:
      backend:
        ipv4_address: 10.0.0.101

  tor:
      build:
        context: ./
        dockerfile: dockerFiles/tor_docker
      networks:
          backend:
              ipv4_address: 10.0.0.102

  mongo:
    image: mongo
    container_name: mongo-db
    volumes:
        - ./data/db:/data/db
    ports:
        - "27017:27017"
    networks:
        backend:
            ipv4_address: 10.0.0.103

  dynamodb-local:
    command: -jar DynamoDBLocal.jar -sharedDb -dbPath ./data
    user: root
    image: "amazon/dynamodb-local:latest"
    container_name: dynamodb-local
    volumes:
      - "./data/dynamo-data/testDataVolume:/home/dynamodblocal/data"
    working_dir: /home/dynamodblocal
    networks:
      backend:
          ipv4_address: 10.0.0.104

  postgres:
    image: postgres:9.6
    environment:
      - POSTGRES_USER=airflow
      - POSTGRES_PASSWORD=airflow
      - POSTGRES_DB=airflow
      - PGDATA=/var/lib/postgresql/data/pgdata
    volumes:
      - ./data/pgdata:/var/lib/postgresql/data/pgdata
    logging:
      options:
        max-size: 10m
        max-file: "3"
    networks:
      backend:
        ipv4_address: 10.0.0.105

  webserver:
    image: puckel/docker-airflow:latest
    restart: always
    build:
      context: https://github.com/puckel/docker-airflow.git#1.10.9
      args:
        AIRFLOW_DEPS: gcp_api,s3
        PYTHON_DEPS: sqlalchemy==1.3.0 markupsafe==2.0.1 wtforms==2.2 boto3~=1.24.22 logdna~=1.18.2 scikit-learn==0.24.2 gevent==21.12.0 lxml==4.9. simplejson==3.17.6 elasticsearch==8.2.3 pymongo==4.1.1 celery==4.4.7 redis==4.3.3 BloomFilter~=0.1.0 schedule gensim==4.2.0 beautifulsoup4~=4.11.1 bs4~=0.0.1 eventlet==0.33.1 nltk~=3.7 validators==0.20.0 urllib3~=1.26.9 stem~=1.8.0 requests[socks]==2.28.0 Pillow==9.1.1 termcolor~=1.1.0 raven~=6.10.0 thefuzz~=0.19.0 arrow~=1.2.2 pydload~=1.0.9 onnxruntime~=1.11.1 scikit-image~=0.19.2 pydantic~=1.9.1 opencv-python~=4.6.0.66 opencv-python~=4.6.0.66
    depends_on:
      - postgres
      - redis
    environment:
      - LOAD_EX=n
      - FERNET_KEY=46BKJoQYlPPOexq0OhDZnIlNepKFf87WFwLbfzqDDho=
      - EXECUTOR=Local
    logging:
      options:
        max-size: 10m
        max-file: "3"
    volumes:
      - ./dags:/usr/local/airflow/dags
      - ./config/airflow.cfg:/usr/local/airflow/airflow.cfg
    ports:
      - "8080:8080"
    command: webserver
    healthcheck:
      test: ["CMD-SHELL", "[ -f /usr/local/airflow/airflow-webserver.pid ]"]
      interval: 30s
      timeout: 30s
      retries: 3
    networks:
      backend:
        ipv4_address: 10.0.0.106

  scheduler:
    image:  puckel/docker-airflow:latest
    restart: always
    depends_on:
      - webserver
    volumes:
      - ./dags:/usr/local/airflow/dags
    environment:
      - LOAD_EX=n
      - FERNET_KEY=46BKJoQYlPPOexq0OhDZnIlNepKFf87WFwLbfzqDDho=
      - EXECUTOR=Local
    command: scheduler
    networks:
      backend:
        ipv4_address: 10.0.0.107



networks:
  backend:
    driver: bridge
    ipam:
      driver: default
      config:
      - subnet: 10.0.0.0/24
